// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrDAA-fXslbs27bLO8ZrM6Y75o3ojkhgY',
    appId: '1:556644431806:web:ad21c2e08f9ef4e80f6bef',
    messagingSenderId: '556644431806',
    projectId: 'smart-blood-108',
    authDomain: 'smart-blood-108.firebaseapp.com',
    storageBucket: 'smart-blood-108.firebasestorage.app',
    measurementId: 'G-CP963GP2WK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-HRRmV-yZ3TbDD9N2LjkxlGjpXdftYSc',
    appId: '1:556644431806:android:35dd1ccfa227df5a0f6bef',
    messagingSenderId: '556644431806',
    projectId: 'smart-blood-108',
    storageBucket: 'smart-blood-108.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbBb54EscK3fcnf-lU8fc9moeE45B6vew',
    appId: '1:556644431806:ios:c9db9628f01a5f090f6bef',
    messagingSenderId: '556644431806',
    projectId: 'smart-blood-108',
    storageBucket: 'smart-blood-108.firebasestorage.app',
    iosBundleId: 'com.example.smartBlood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbBb54EscK3fcnf-lU8fc9moeE45B6vew',
    appId: '1:556644431806:ios:c9db9628f01a5f090f6bef',
    messagingSenderId: '556644431806',
    projectId: 'smart-blood-108',
    storageBucket: 'smart-blood-108.firebasestorage.app',
    iosBundleId: 'com.example.smartBlood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrDAA-fXslbs27bLO8ZrM6Y75o3ojkhgY',
    appId: '1:556644431806:web:44f1fa4cb485991e0f6bef',
    messagingSenderId: '556644431806',
    projectId: 'smart-blood-108',
    authDomain: 'smart-blood-108.firebaseapp.com',
    storageBucket: 'smart-blood-108.firebasestorage.app',
    measurementId: 'G-S3Q823KNJT',
  );
}
